### ISSUE TITLE
0 day vulnerability to be patched 

### ISSUE THREAD

**Issue by muhammaddadu** [netmikey/logunit#2]
https://thehackernews.com/2021/12/extremely-critical-log4j-vulnerability.html

**Comment by netmikey** [comment]
Even though I hope no-one relies on our BOM to resolve logging framework versions, you are right: we shouldn't rely on libraries with known vulnerabilities.

I have a patch release coming up to Maven Central that updates just the transitive dependencies to their latest versions.

**Comment by netmikey** [comment]
This is fixed in [v1.1.1](https://github.com/netmikey/logunit/releases/tag/v1.1.1).
