### ISSUE TITLE
Last release requires java 11

### ISSUE THREAD

**Issue by iNikem** [netmikey/logunit#3]
Recently release `logunit-logback:1.1.1` publishes [Gradle module file](https://repo.maven.apache.org/maven2/io/github/netmikey/logunit/logunit-logback/1.1.1/logunit-logback-1.1.1.module) which declares that this module requires java 11:

```
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
```

This contradicts README claim that java 8 is supported. Probably the easiest way to fix this is to configure java compiler in your build scripts with `release=8` option: https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_cross_compilation

**Comment by netmikey** [comment]
Thanks for reporting!

Fixed in [v1.1.2](https://github.com/netmikey/logunit/releases/tag/v1.1.2)
